### PR TITLE
[FIX] README.md

### PR DESCRIPTION
**Pull request by mileo**

### CODE REVIEW

**Comment by dreispt** [comment]
Thanks!
Note that those installation instructions are still incomplete.

**Comment by mileo** [comment]
Yes, but i'm already testing =D

image

Does the project already have a defined roadmap?

**Comment by dreispt** [comment]
It does, but it's in my head 😸.
I have to write it down. Somo topics:

1st priority is to get pip + virtualenv installation working like a breeze.
Then make GUI module installation work with pip, if module not locally available, so that Config wizards just work.
And then I'll look into providing common UX and base geatures, such as better search and audit logs.

**Comment by mileo** [comment]
Nice, If you can we can make a hangout next week. I would love to help with this project.

**Comment by dreispt** [comment]
We can arrange that.
My address is `dreis<dot>pt<at>gmail<dot>com`

**Pull request merged**
